env:
  es2021: true
  node: true
extends:
  - airbnb-typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - '@typescript-eslint'
  - import
rules: {
  "react/jsx-filename-extension": 0
}
